### ISSUE TITLE
Adding age bin 80-89 and 90+

### ISSUE THREAD

**Issue by nknox** [Public-Health-Bioinformatics/DataHarmonizer#102]
Is it possible to add an age bin for 80-89 and another for 90+?

Our partners have indicated that this would add more granularity to the data given they test several individuals above 100 yo.

**Comment by griffie** [comment]
Done! I added new 80 - 89, 90 - 99, and 100+ bins.

**Comment by ivansg44** [comment]
@ddooley will refresh the app with @griffie's changes

**Comment by ddooley** [comment]
This is now done!
