### ISSUE TITLE
Organism Example Update

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#106]
Noticed that example the `organism` field says "Severe acute respiratory coronavirus 2" but that is no longer an acceptable input. It appears to have been changed to "Severe acute respiratory syndrome coronavirus 2". Have updated to vocab sheet and the SOP example to the new label.

I think people might get very frustrated if we don't get this updated quickly because it's a field everyone has to use and there isn't any source telling them what it's actually supposed to be (from what I can tell).

**Comment by cmrn-rhi** [comment]
Then again, since there is the drop-down menu there isn't as much urgency.

**Comment by ivansg44** [comment]
@cmrn-rhi Can you confirm if this is still an issue?

**Comment by ddooley** [comment]
I think the problem was in the test datasets and now those values are adjusted to match the menu items.  Seems that way on http://genepio.org/DataHarmonizer/main.html at any rate.

**Comment by cmrn-rhi** [comment]
@ivansg44 It's no longer a problem on the current master branch. 
I agree with @ddooley that the issue was most probably resolved when the values were updated.
