### ISSUE TITLE
CNPHI Export... Patient Travelled

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#107]
If a there is data in the DataHarmonizer template under `travel history` shouldn't the CNPHI export say `yes` under `Patient Travelled`? Even when there is no data in the `Country of Travel\|Province of Travel\|City of Travel\|Travel start date\|Travel End Date` field; it could be that a user didn't fill in those optional fields and just chose to use `travel history`.

![image](https://user-images.githubusercontent.com/48695054/95042322-59ffef80-068e-11eb-9cda-c22ef1584050.png)

**Comment by ddooley** [comment]
Looks like "travel history" content should be added as a logic trigger for patient travelled.

**Comment by ddooley** [comment]
This is now done in patient-travelled pull request.
