### ISSUE TITLE
CNPHI Export - Travel History

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#112]
Incorrect mappings for travel history.

DataHarmonizer: **destination of most recent travel (city)**
_is mapping to..._
CNPHI: **Country of Travel**

DataHarmonizer: **destination of most recent travel (country)**
_is mapping to..._
CNPHI: **City of Travel**

**BEFORE** (DataHarmonizer format):
![image](https://user-images.githubusercontent.com/48695054/96048543-9ddfbb00-0e2b-11eb-88f5-22cb4126c62b.png)

**AFTER** (CNPHI export):
![image](https://user-images.githubusercontent.com/48695054/96048606-af28c780-0e2b-11eb-8dfd-99cd03ce48fb.png)

**Comment by ddooley** [comment]
Good catch. I'll fix today.
