### ISSUE TITLE
CNPHI Export - Multiple Symptom Export

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#114]
Data Harmonizer is separating multiple symptoms by `;` but CNPHI import requires entries be separated by `~`.

**Comment by ddooley** [comment]
Looks like that the only multiselect field at moment.  It looks like we should add another parameter, a "separator" field, for export formats, assuming same separator is used throughout the output's multi-selects.

**Comment by cmrn-rhi** [comment]
Based on what the [CNPHI LaSER Upload Guide](https://www.cnphi-rcrsp.ca/errs/faces/orders/uploadGuide.xhtml) says, I think that applies throughout the output's multi-selects.

**Comment by ddooley** [comment]
~ is implemente on signs and symptoms field now.  No other multi-select fields are brought into CNPHI export.
