### ISSUE TITLE
CNPHI Export - "Animal Type" Issue.

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#115]
CNPHI "Animal Type" field doesn't accept Humans.
Looks like we are mapping "host (common name)" to "Animal Type"; can we do so but omit "human"?

**CNPHI Field Context:**

Field: **Specimen Source**
Input: Human, Animal, Environment

Field: **Animal Type**
Input: Bat, Cat, Chicken, Civets, Cow, Dog, Lion, Pangolin, Pig, Pigeon, Tiger, **~Human~**

**Comment by cmrn-rhi** [comment]
@ddooley any estimated time on when this is could be resolved?

CNPHI will reject "Human" is listed under "Animal Type"; so ideally whenever "Human" is picked for "Specimen Source", "Animal Type" will remain empty.

**Comment by ddooley** [comment]
Ok, I think the fix is in.  Human is moved over to 'Specimen Source'

![image](https://user-images.githubusercontent.com/4000582/98594381-6e389d00-2289-11eb-9127-1705c68942c4.png)

**Comment by cmrn-rhi** [comment]
Beautiful! Thank you!
