### ISSUE TITLE
CNPHI Export - .CSV option

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#116]
The DataHarmonizer allows for export to the CNPHI template in .xls, but CNPHI only accepts .csv
Would be very helpful to have the option to export to .csv, ideally as the CNPHI export default.

:star: Thanks to Sarah Savić Kallesøe for identifying this issue!

**Comment by cmrn-rhi** [comment]
@ddooley would it be possible to get this fixed ASAP?

**Comment by ddooley** [comment]
It is fixed on DataHarmonizer2.  But I could push the change separately - to have .csv now if you like?

**Comment by ddooley** [comment]
Done directly to master.  Do you want it on the http://genepio.org/DataHarmonizer site too?

**Comment by cmrn-rhi** [comment]
Yes, Thank you! We'd like it implemented wherever people are using DataHarmonizer to export to CNPHI.

**Comment by cmrn-rhi** [comment]
Should these changes already be reflected in DataHarmonizer2? If so it is still only allowing me to export CNPHI to `.xls` .

**Comment by ddooley** [comment]
The https://genepio.org/DataHarmonizer/ site is updated now.  The DataHarmonizer2 site is just for testing and will be pushed over to the former site when ready.

**Comment by ddooley** [comment]
problem resolved; additional step required to show change in file suffix in form with change in selected output format - in DataHarmonizer2
