### ISSUE TITLE
Provenance - validation info only outputting to 1 row

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#117]
The `provenance` validation version information is only being outputted to one row. Would like to see it for all rows so if the data gets subset or merged (etc.) the version information will be present for all specimen.

![image](https://user-images.githubusercontent.com/48695054/97497751-3bf17c00-1928-11eb-8ef5-622ba315a5e6.png)

**Comment by cmrn-rhi** [comment]
Tested on **DataHarmonizer2**, don't see `provenance` on DataHarmonizer1.

**Comment by ddooley** [comment]
Yes - that was a design question.  Can easily do that.

**Comment by ddooley** [comment]
Change implemented
