### ISSUE TITLE
Suggestion: Required Fields

### ISSUE THREAD

**Issue by sarahsavickallesoe** [Public-Health-Bioinformatics/DataHarmonizer#118]
Hi,

Considering that we want submitters to include as much information as possible beyond the required fields, perhaps we could amend the DH to show the purple optional columns alongside the yellow required ones when "Show required columns" is selected.

As it stands, showing just the required column headers may not be enabling or encouraging people to add in additional information.

Cheers,

Sarah

**Comment by cmrn-rhi** [comment]
After today's CanCOGeN meeting, we're thinking add an additional `Show required and recommended columns` option that displays both yellow and purple fields.

**Comment by ddooley** [comment]
This is finally added in current main branch!
