### ISSUE TITLE
DataHarmonizer2 - Validation issue (sequence submitted by, geo_loc_name (province/territory))

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#119]
Testing valid data and for some reason "sequence submitted by" is marking valid data as invalid. The only way to overcome this is to reselect the value from the picklist - see `Public Health Ontario (PHO)` in screenshot of validated sheet.

![image](https://user-images.githubusercontent.com/48695054/98051069-eb769480-1de7-11eb-9ddb-1842f6255959.png)

**Comment by ddooley** [comment]
This often means a space or possibly an other UTF braces code was used in encoding the string.  I'll retype in source vocabulary, usually that fixes.

**Comment by cmrn-rhi** [comment]
Same thing appears to have happened with `Newfoundland and Labrador` under `geo_loc_name (province/territory)`. Perhaps there was an issue with the last vocabulary import as all the values experiencing this problem were changed in the last vocabulary update. 

![image](https://user-images.githubusercontent.com/48695054/98052478-31812780-1deb-11eb-91d7-47799fa14880.png)

**Comment by cmrn-rhi** [comment]
In both these documents:
1. I imported the file, 
2. selected valid terms from the picklists,
3. then saved it from DataHarmonizer, 
4. and then reimported it and they were deemed invalid again.

**Comment by ddooley** [comment]
Ah, that discounts that explanation.  Must be an extra space getting inserted in menu item selection.  Will check.

**Comment by cmrn-rhi** [comment]
I was running a serious of experiments, still getting weird character inserts (observable in UTF-7), but then I refreshed the window and started running another set and it doesn't appear to be happening anymore. Will run a couple more checks to confirm.

**Comment by cmrn-rhi** [comment]
Unable to reproduce using the same source data and branch. Will close this issue for the time being and reopen if this issue arises again.
