### ISSUE TITLE
DataHarmonizer Provenance in CNPHI export

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#131]
CNPHI has agreed that we can output the `DataHarmonizer provenance` version information into a (free-text) column called `additional comments`.

-------------
###### **Example DH-CNPHI Export CSV:**
-------------
![image](https://user-images.githubusercontent.com/48695054/99156193-e16c5580-2673-11eb-9f37-40bc9a98dbf3.png)

-------------
###### **Example Successful CNPHI Upload:**
-------------
![image](https://user-images.githubusercontent.com/48695054/99156212-ff39ba80-2673-11eb-8c34-44703e4cb13c.png)

**Comment by ddooley** [comment]
done!
