### ISSUE TITLE
COVID-19 Vocab Update

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#134]
COVID-19 vocab update due to changes in DataHarmonizer Templates "CanCOGEn-COVID" tab. To be completed before next release.

**Field:** geo_loc_name (province/territory)
**Value:** Yukon
**Comments:** Changed from "Yukon Territory" to "Yukon" to be compatible with CNPHI upload.

**Field:** signs and symptoms
**Value:** Abnormal lung auscultation
**Comments:** Corrected spelling mistake "ausculation" -> "auscultation".

**Comment by ddooley** [comment]
implemented
