### ISSUE TITLE
CanCoGen-vocabulary-fix branch Field Testing

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#145]
## Software version number fields
**Branch:** CanCoGen-vocabulary-fix

`consensus sequence method version` only accepts numbers with a single period.
* Example: "1" or "1.0", does not accept "1.0.1" and so forth.

Not the end of the world, people can put "101" instead - but if they need to do so we should include that in the guidance.

Also, this is in contrast to `lineage/clade analysis software version` which is able to accept "1.0.1", the downside is that it also accepts non-numbers. Whatever solution is chosen it is probably best to make these `version` fields consistent in their implementation.

---
**Attachments:**
[DH-Test_2021-02-19 (CanCOGeN vocabulary fix).zip](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/6018354/DH-Test_2021-02-19.CanCOGeN.vocabulary.fix.zip)

**Comment by cmrn-rhi** [comment]
## General

Tested the following fields and found they behaved as expected (appropriate valid and invalid feedback based on requirements of field and data types).

- sample received date
- purpose of sampling
- host residence geo_loc name (country)
- host vaccination status
- vaccine name
- number of vaccine doses received
- exposure contact level
- amplicon size
- library preparation kit
- flow cell barcode
- amplicon pcr primer scheme
- raw sequence data processing method
- dehosting method
- depth of coverage threshold
- lineage/clade name
- lineage/clade analysis software name
- lineage/clade analysis software version
- variant designation
- variant evidence
- gene name 3
- diagnostic pcr protocol 3
- diagnostic pcr Ct value 3

## Required Field
`sample collection date precision` behaved as expected but should be a **required** field.

## Auto-Date Formatting

The following fields have the auto-date formatting to ensure there are value for year, month, and day - but doesn't have a paired precision date column to clarify that these are not actually dated "YYYY-01-01". Is this necessary for non-mandatory fields? **NOTE: This has also being discussed in #137**

- symptom onset date
- vaccination date
- most recent travel departure date
- most recent travel return date
- sequencing date

## Misc
Changed `number of base pairs seequenced` to `number of base pairs sequenced` in the [DataHarmonizer `CanCoGen COVID` template](https://docs.google.com/spreadsheets/d/1jPQAIJcL_xa3oBVFEsYRGLGf7ESTOwzsTSjKZ-0CTYE/edit#gid=886509415).

---
**Attachments:**
[DH-Test_2021-02-21 (CanCOGeN vocabulary fix).zip](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/6018365/DH-Test_2021-02-21.CanCOGeN.vocabulary.fix.zip)

**Comment by ddooley** [comment]
I think "consensus sequence method version" has been renamed "consensus sequence software version" ?  The only way to enable multi-dot versioning is to convert this field from a decimal data type to a string. I have done that.

"sample collection date precision" is now required.

The auto-date formatting issue has been solved.
