### ISSUE TITLE
Allow set default template from query string in URL

### ISSUE THREAD

**Issue by Takadonet** [Public-Health-Bioinformatics/DataHarmonizer#147]
Be nice to have ability to indicate what is the default template to load from URL . If none provided, default to first in the list?

**Example:**

http://hosted.com/DataHarmonizer/main.html?template=CanCOGeN%20Covid-19 would load the _CanCOGeN Covid-19_ template. 

Believe would be parameterization of [template_label](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/blob/483acf93da86b0b3e43a31d1956bf5eb2c8261b1/script/main.js#L1201) and having a fallback if none was given in query string.

**Comment by ddooley** [comment]
Hi Philip,
I think what you are looking for exists, though not promoted in the documentation. If the template parameter points to a subfolder of the local DH template/ folder, it will load that template.
E.g.
http://genepio.org/DataHarmonizer/main.html?template=canada_covid19
http://genepio.org/DataHarmonizer/main.html?template=gisaid

Let me know if that's what you were thinking of! We chose to use the folder name, which would typically be shorter than the spelled out template label, and less subject to change over time.

Damion

**Comment by ddooley** [comment]
One thing to note is that this allows access to templates that aren't baked into the template list supplied at top of main.js and which are shown in the menu system.

**Comment by Takadonet** [comment]
Exactly what I was looking for!

**Comment by ddooley** [comment]
Great. I thought it would be useful, especially for customization.

**Comment by ddooley** [comment]
Note updated documentation, not quite complete, but if you are mulling custom templates, here it is: https://github.com/Public-Health-Bioinformatics/DataHarmonizer/wiki/DataHarmonizer-Templates
