### ISSUE TITLE
CanCOGeN template - LIMS export change to Specimen source field label

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#148]
Currently the CNPHI export from the CanCOGeN template outputs an extra field not in the template called "Specimen Type" where the sample is classified using hard coded logic as Human, Environmental or Animal. In the NML LIMS export, this field should be renamed as "PH_SPECIMEN_SOURCE" and the values tweaked to HUMAN, ENVIRO and ANIMAL.

**Comment by ddooley** [comment]
This is included in Cancogen nml lims v0.1 #155 pull request.
