### ISSUE TITLE
CanCOGeN export to LIMS: Patient Symptomatic needs to be changed in LIMS export

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#149]
Currently, there is a field called Patient Symptomatic with values "yes" or "no" based on whether there are symptoms listed, that is exported in the CNPHI export file based on hard coded logic (this field is not in our template). This field should be renamed VE_SYMP_AVAIL in the NML LIMS export. Values should be renamed as Y and N.

**Comment by ddooley** [comment]
This is included in Cancogen nml lims v0.1 #155 pull request.
