### ISSUE TITLE
CanCOGeN template to LIMS: CNPHI things not in LIMS that should be removed

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#150]
There are some fields output in the CNPHI export from the CanCOGeN template that are not present in NML LIMS that should not be output in the LIMS export. These fields are: "Related Specimen ID|Related Specimen Relationship Type", "Test Requested", and "Patient Travelled".

**Comment by ddooley** [comment]
This is implemented in Cancogen nml lims v0.1 #155
