### ISSUE TITLE
PHA4GE template export to Biosample: need logic to export additional field "attribute package"

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#151]
The Biosample export should contain an additional field not in the PHA4GE template called "attribute_package". The values are "Pathogen.cl" and "Pathogen.env". Pathogen.cl means the sample is a clinical pathogen and this value should be output if the sample has host information (i.e. most will be human clinical samples so most should have Pathogen.cl as a value). Anything that doesn't have host info, should be output as Pathogen.env.

**Comment by ddooley** [comment]
Should this be true of CanCoGen to biosample export too?  And should CanCoGen also have a blank host_disease_stage field?

**Comment by griffie** [comment]
Yes. But there are probs a number of changes that need to be made for the CanGOGeN to biosample mapping. Haven't got there yet...

**Comment by ddooley** [comment]
Its just that I may be able to have identical code for both.  We'll see.

**Comment by griffie** [comment]
In that case, then yes.

**Comment by ddooley** [comment]
This has been implemented!
