### ISSUE TITLE
CanCOGeN template to NML LIMS export: change of null value labels

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#154]
In the LIMS export from the CanCOGeN template, the null values need labels changes.

NA | Not Applicable
-- | --
MISSING | Missing
NOT_COLLECTED | Not Collected
NOT_PROVIDED | Not Provided
RESTRICTED_ACCESS | Restricted Access

**Comment by ddooley** [comment]
Now implemented in NML LIMS branch.
