### ISSUE TITLE
PHA4GE template to Biosample export: need code to add host_disease_stage field

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#156]
Currently, there is no info recorded for "host_disease_stage" in the PHA4GE template, but that field needs to appear in the NCBI Biosample export. Can you add some code to have that field output in the export although it will be blank?

**Comment by ddooley** [comment]
Do you mean blank or should it have a default "Missing" value?

**Comment by ddooley** [comment]
Ok, this is now in master.
