### ISSUE TITLE
CanCOGeN template: Upload new SOP

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#157]
Can you please upload the latest version of the data curation SOP?
[CanCOGeN Metadata Curation SOP_2.0.pdf](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/6093676/CanCOGeN.Metadata.Curation.SOP_2.0.pdf)

**Comment by ddooley** [comment]
New SOP uploaded and will be included in next release.
