### ISSUE TITLE
DataHarmonizer-0.13.18: NML format export field `VD_SEX` has opposite values with `host gender`

### ISSUE THREAD

**Issue by lindaxiang** [Public-Health-Bioinformatics/DataHarmonizer#163]
Hi team,

I was using DataHarmonizer-0.13.18 to export NML format and find that `VD_SEX` field in the output file is populated with opposite value of original `host gender` in the DataHarmonizer excel table.
DataHarmonizer Excel talble:
<img width="114" alt="Screen Shot 2021-03-25 at 1 35 12 PM" src="https://user-images.githubusercontent.com/7522294/112517704-ff0ea180-8d6e-11eb-867b-b105495ee6c4.png">

NML csv table:
<img width="66" alt="Screen Shot 2021-03-25 at 1 33 46 PM" src="https://user-images.githubusercontent.com/7522294/112517606-e0a8a600-8d6e-11eb-8228-10ca6ba515c2.png">

Can you please clarify this is the correct intention?

Thank you!

Linda

**Comment by ddooley** [comment]
This is an error in the conversion table - the values should be flipped.  Thanks for spotting this.  We are doing a vocabulary correction and DH release tonight.  Now, we were under the impression that this format hasn't been in use yet.  Were you doing data import using this option into NML LIMS?

**Comment by lindaxiang** [comment]
@ddooley No worries. I was just trying the tool and spotting the issue.  
Glad it helps. 

-Linda

**Comment by lindaxiang** [comment]
Just tried the latest version and it works well. Thanks for fixing the issue!
