### ISSUE TITLE
check for duplicate sample IDS

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#165]
Some datasets are being submitted with duplicate samples. In large datasets, duplications are difficult to catch.

Can the DH perform a check for duplicate samples and highlight them in red if detected, and present a warning message?

This can be automatic or the check could be performed upon validation or some other checking process?

**Comment by ddooley** [comment]
We can make this a part of the validation process.  But it has to involve a manual setting per field to check.  We can't just assume that first column which usually has an identifier must have unique values.  Will think about what that setting would be called.

**Comment by ddooley** [comment]
I have the test code for this going.  Now by marking a field as having datatype xs:unique , the field will be tested for uniqueness.  blank values/rows are ignored.
