### ISSUE TITLE
Autopopulate age bin with "Missing" if the age value is a null value.

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#167]
Right now we have to manually fill in "age bin" if a null value is entered in the age value column. When you are dealing with a lot of samples at once, this is cumbersome.

Can we get the DH to autopopulate the age bin column with "Missing" if the age value is a null value?

**Comment by griffie** [comment]
Adding to this: If a null value is entered into the age value field and the bin is left empty, can the bin field be populated with the same null value when the user hits "validate"?

If the user enters a null value for age, but also enters a bin, then that can be left as is.

**Comment by ddooley** [comment]
I presume you want this for host age unit as well?

**Comment by griffie** [comment]
Yes please!

**Comment by ddooley** [comment]
Done!
