### ISSUE TITLE
Identifying invalid cells more quickly (skip to invalid cell rather than just the row)

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#169]
Currently you can select "Show invalid row" upon validation which will only show rows with errors in them.

But when working with big datasets, the errors are not always in the same column and it is a pain to have to sift through all the columns if you have many rows with errors.

Can we have a feature that enables the user to jump to the cell with the error (maybe "Jump to cell with error" which would work on the top row, which you can fix then move to the next error in the same row. Once a row is fixed, you can move to the next row? That way you can systematically fix all the errors instead of wildly scrolling.

Here is a mock dataset with sporadic errors that a user would have to search through the columns to find.
[find_nonvalid_cells_test set.xlsx](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/6338943/find_nonvalid_cells_test.set.xlsx)

**Comment by ddooley** [comment]
Perhaps a "Next Error" button after the loaded file display in upper right - that would show after one pressed Validate - would be the most user friendly way to jump ahead. It would just look at where the cursor is (or start of display), and advance to the next error cell on that row or next row error cell.

**Comment by wwhsiao** [comment]
I like the Next Error idea.
