### ISSUE TITLE
PHA4GE template: reorder BioSample export fields

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#176]
I updated the field names in the DH template and tested the biosample export.

Can we reorder the fields so they match the submission form?

The correct order can be found in the file attached.
[NCBI field names for DH.xlsx](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/6401987/NCBI.field.names.for.DH.xlsx)

**Comment by ddooley** [comment]
I've updated the Biosample export field list.  Note that it has some extra entries?  It now reads:

   ['sample_name',             []],
    //sample_title
    ['bioproject_accession',    []],
    ['organism',                []],
    ['collected_by',            []],
    ['collection_date',         []],
    ['geo_loc_name',
      [
        'geo_loc_name (country)',
        'geo_loc_name (state/province/territory)',
        'geo_loc name (county/region)',
        'geo_loc_name (city)'
      ]
    ],
    ['host',                    []],
    ['host_subject_id',         []],
    ['host_disease',            []],
    ['isolate',                 []],
    ['isolation_source',     
      ['anatomical material','anatomical part','body product','environmental material','environmental site','collection device','collection method']],
    ['antiviral_treatment_agent',
    ['collection_device',       []],
    ['collection_method',       []],
    ['date_of_prior_antiviral_treat',  []],
    ['date_of_prior_sars_cov_2_infection',  []],
    ['date_of_sars_cov_2_vaccination',  []],
    ['sequenced_by',            []],
    ['sample collection date',  []],
    ['exposure_event',          []],
    ['geo_loc_exposure',        []], 
    ['gisaid_accession',        []],
    ['gisaid_virus_name',       []],
    ['host_age',                []],
    ['host_anatomical_material', []],
    ['host_anatomical_part',    []],
    ['host_body_product',       []],
    ['environmental_material',  []],
    ['environmental_site',      []],
    ['host_disease_outcome',    []],
    ['host_health_state',       []],
    ['host_recent_travel_loc',  []],
    ['host_recent_travel_return_date',  []],
    ['host_sex',                []],
    ['host_specimen_voucher',   []],
    ['host_subject_id',         []],
    ['lat_lon',                 []],
    ['passage_method',          []],
    ['passage_number',          []],
    //['passage_history',         []], //passage_number?
    ['prior_sars_cov_2_antiviral_treat', []],
    ['prior_sars_cov_2_infection', []],
    ['prior_sars_cov_2_vaccination', []],
    ['date_of_sars_cov_2_vaccination', []],
    ['purpose_of_sampling',     []],
    ['purpose_of_sequencing',   []],
    ['sars_cov_2_diag_gene_name_1',   []],
    ['sars_cov_2_diag_gene_name_2',   []],
    ['sars_cov_2_diag_pcr_ct_value_1',   []],
    ['sars_cov_2_diag_pcr_ct_value_2',   []],
    ['sequenced_by',            []],
    ['vaccine_received',        []],
    ['virus_isolate_of_prior_infection', []],

    ['attribute_package',       []], //not in biosample sort list

   //The following fields are not in NCBI Biosample but were listed in our code
    ['description',             []],
    ['lab_host',                []],
    ['host_disease_stage',      []],
    ['gene_name_1',             []],
    ['diagnostic_PCR_CT_value_1',  []],
    ['gene_name_2',             []],
    ['diagnostic_PCR_CT_value_2', []]

**Comment by griffie** [comment]
Yep, the ones that are missing are junk. :)

**Comment by ddooley** [comment]
Where do you want attribute_package to show?

**Comment by griffie** [comment]
Oh right, you can pop attribute_package right after bioproject accession, thanks.

**Comment by ddooley** [comment]
Ok, done in draft
