### ISSUE TITLE
PHA4GE template: sample type fields need to report separately and in isolation source field

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#177]
The sample type fields (anatomical part, anatomical material, body product, environmental material, environmental site, collection device, collection method) are named slightly differently in the Biosample export. I've made sure to add those different names in the DH template.

If they are populated, the values need to export to the renamed fields (e.g. anatomical part needs to move to host_anatomical_part) BUT ALSO all of their VALUES (only values) need to be concatenated in "isolation_source" and separate by a colon e.g.
anatomical part = Nasopharynx (NP)
collection device = Swab
isolation_source = Nasopharynx (NP): Swab

I tried to indicate this in the PHA4GE biosample export column but I'm sure I didn't do it right.

Can you please check it?

**Comment by ddooley** [comment]
So that is working except the separator is a vertical bar | instead of a colon. Is it supposed to be a colon?

**Comment by griffie** [comment]
Yeah, NCBI is very particular about the separator. They want a colon. Not even a comma, but a colon.

**Comment by ddooley** [comment]
Ok, done in draft. I had to change DataHarmonizer template parameters a little bit.
