### ISSUE TITLE
PHA4GE template: geo_loc name concatenation

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#178]
In the the PHA4GE template there are several geo_loc fields for sample collection i.e.
geo_loc name (country)
geo_loc name (state/province/territory)
geo_loc name (county/region)
geo_loc name (city)

destination of most recent travel i.e.
destination of most recent travel (city)
destination of most recent travel (state/province/territory)
destination of most recent travel (country)

There is only one field for geo_loc in the Biosample form.

These fields need to be concatenated.
So 
geo_loc name (country)
geo_loc name (state/province/territory)
geo_loc name (county/region)
geo_loc name (city)
all need to go into geo_loc name separated by a colon. But here is the trick, they only allow 2 bits in the field. So we need the country name and then whatever the most granular info is in the other 3 e.g.
geo_loc name (country) = Canada
geo_loc name (state/province/territory) = British Columbia
geo_loc name (county/region) = Not Applicable
geo_loc name (city) = Vancouver
geo_loc name = Canada:Vancouver

Same thing for travel. All the travel fields need to be concatenated in host_recent_travel_loc e.g.
destination of most recent travel (city) = Not Provided
destination of most recent travel (state/province/territory) = Ontario
destination of most recent travel (country) = Canada
host_recent_travel_loc = Canada:Ontario

If there's a null value, don't count that.

I tried to express this in the export column but I probs didn't do it right.
Can we do this?

**Comment by ddooley** [comment]
I've implemented this now in new draft. 

Question: should isolation_source, which is also a concatenation of other fields, have null values removed in them? E.g. right now we're getting things like: 
"Not Applicable:Intestine:Missing:Missing:Wet market:Blood Collection Tube:Necropsy"

**Comment by griffie** [comment]
Yes, null values removed please! Thank you!

**Comment by ddooley** [comment]
Ok, done.  Changes uploaded to master.
