### ISSUE TITLE
PHA4GE template: reorder fields in SRA export

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#179]
Can we please reorder the fields in the SRA export so they resemble the submission form?

They should be in this order pretty please:
sample_name
bioproject_accession
biosample_accession
library_ID
title
library_strategy
library_source
library_selection
library_layout
platform
instrument_model
design_description
filetype
filename
amplicon_pcr_primer_scheme
amplicon_size
sequencing_protocol
bioinformatics_protocol
sequence_submitter_contact_email

**Comment by ddooley** [comment]
The current DataHarmonizer also has these SRA fields. Do we keep these too?
sequencing_protocol_name   --- same as "sequencing_protocol" ??
raw_sequence_data_processing_method 
dehosting_method
filename 2

**Comment by griffie** [comment]
Gah! My mistake. Can you take out sequencing_protocol and bioinformatics_protocol? I was looking at an older version.
We swapped the others in to be more specific.

Can you please add the following after "amplicon_size":
sequencing_protocol_name 
raw_sequence_data_processing_method
dehosting_method
filename2

**filename 2 should be filename2

Thanks!

**Comment by ddooley** [comment]
maybe filename2 should follow filename field?

**Comment by griffie** [comment]
Yes! Good thinking....

**Comment by ddooley** [comment]
Ok, these and all the other changes are pushed to master! Not sure if you need a release?
