### ISSUE TITLE
PHA4GE template: reorder fields in GenBank export

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#180]
Can we please reorder the fields in Genbank export from the PHA4GE template to resemble the submission form?

They should be in this order please:
biosample_accession
sample_name
assembly_method
assembly_method_version
genome_coverage
sequencing_technology
reference_genome
filename

**Comment by griffie** [comment]
Good catch! No, we don't want that I don't think. I just removed it.

**Comment by ddooley** [comment]
ok, done in draft
