### ISSUE TITLE
GISAID export from PHA4GE template: add new field Sampling Strategy

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#182]
The GISAID folks have added a new field called Sampling Strategy that corresponds to our Purpose of Sequencing. I've updated the DH template. Can the Sampling Strategy field appear after the "Additional location information" field in the export please?

I also removed the DataHarmonizer provenance field as that may screw up GISAID submission.

**Comment by ddooley** [comment]
Done on draft version of DH.
