### ISSUE TITLE
New order of fields in Biosample export form PHA4GE template

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#184]
To match the new SARS-CoV-2-specific Biosample template, can we please reorder the fields?
I think the only new field we need is called "sample_title", but we don't map to this from our fields so it will be blank.

The new order can be found in the attached sheet. (Don't worry about all the other stuff like colour-coding and the instructions.)

[SARS-CoV-2.cl.1.0 .xlsx](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/6469359/SARS-CoV-2.cl.1.0.xlsx)

**Comment by ddooley** [comment]
We have these exported fields at moment, in order.  I have questions about the "NOT IN GIVEN TEMPLATE. ..." items:

    ['sample_name',             []],
    ['sample_title',            []],
    ['bioproject_accession',    []],

    ['attribute_package',       []], // NOT IN GIVEN TEMPLATE. WHERE SHOULD IT GO?

    ['organism',                []],
    ['collected_by',            []],
    ['collection_date',         []],
    ['geo_loc_name',            []],
    ['host',                    []],

    ['host_subject_id',         []], // NOT IN GIVEN TEMPLATE. WHERE SHOULD IT GO?

    ['host_disease',            []],
    ['isolate',                 []],
    ['isolation_source',     
      ['anatomical material','anatomical part','body product','environmental material','environmental site','collection device','collection method']],
    ['antiviral_treatment_agent', []],
    ['collection_device',       []],
    ['collection_method',       []],
    ['date_of_prior_antiviral_treat',  []],
    ['date_of_prior_sars_cov_2_infection',  []],
    ['date_of_sars_cov_2_vaccination',  []],

    ['sample collection date',  []], // NOT IN GIVEN TEMPLATE. WHERE SHOULD IT GO?

    ['exposure_event',          []],
    ['geo_loc_exposure',        []], 
    ['gisaid_accession',        []],
    ['gisaid_virus_name',       []],
    ['host_age',                []],
    ['host_anatomical_material', []],
    ['host_anatomical_part',    []],
    ['host_body_product',       []],

    ['environmental_material',  []], // NOT IN GIVEN TEMPLATE. WHERE SHOULD IT GO?
    ['environmental_site',      []], // NOT IN GIVEN TEMPLATE. WHERE SHOULD IT GO?

    ['host_disease_outcome',    []],
    ['host_health_state',       []],
    ['host_recent_travel_loc',  []],
    ['host_recent_travel_return_date',  []],
    ['host_sex',                []],
    ['host_specimen_voucher',   []],
    ['host_subject_id',         []],
    ['lat_lon',                 []],
    ['passage_method',          []],
    ['passage_number',          []],
    ['prior_sars_cov_2_antiviral_treat', []],
    ['prior_sars_cov_2_infection', []],
    ['prior_sars_cov_2_vaccination', []],

    ['date_of_sars_cov_2_vaccination', []], // NOT IN GIVEN TEMPLATE. WHERE SHOULD IT GO?
    
    ['purpose_of_sampling',     []],
    ['purpose_of_sequencing',   []],
    ['sars_cov_2_diag_gene_name_1',   []],
    ['sars_cov_2_diag_gene_name_2',   []],
    ['sars_cov_2_diag_pcr_ct_value_1',   []],
    ['sars_cov_2_diag_pcr_ct_value_2',   []],
    ['sequenced_by',            []],
    ['vaccine_received',        []],
    ['virus_isolate_of_prior_infection', []],

Also given template has a "description" field which we don't have?

**Comment by griffie** [comment]
Attribute package should be removed.

host_subject_id - wait, this one should be in there and should be exporting. It should appear after "host_specimen_voucher". 
I can see in the DH templates. It should be there.

sample collection date should be removed. 
In the DH template, "sample collection date" is ours and should be exporting to the Biosample "collection_date". 

"environmental_material" and "environmental_site" should be included (sorry, that was my bad. We are adding those in).
They should appear after "host_body_product".

date_of_sars_cov_2_vaccination IS in the given template. It should be right after "date_of_prior_sars_cov_2_infection".

**Comment by ddooley** [comment]
Ok thanks. I see I had some duplicate fields in there.  Ordering is now implemented in draft.
