### ISSUE TITLE
SRA export from PHA4GE template: mapping to NCBI platform list from our sequencing instrument list not working

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#185]
In our specification, we offer the user a list of sequencing instruments under "sequencing instrument". Most of these were originally taken form the NCBI list of instruments, so our list is generally compatible with the NCBI list which they call "instrument model".

In the SRA export, NCBI asks for "platform" (the company) and "instrument_model". We now now prefix all instruments with the company name that makes them e.g. Illumina, Oxford Nanopore. 

We can map directly to the "instrument_model" from our "sequencing instrument" field. 
I've tried to map from the instrument names to both the platform and model fields e.g. 

line 884 in DH template: Illumina HiSeq 1000  

Under export_NCBI_SRA:    platform:ILLUMINA|instrument_model:Illumina HiSeq 1000

But nothing shows up in the instrument_model or platform fields in the export.
It's not working.

Can you fix it, pretty please?

**Comment by ddooley** [comment]
This should be fixed in draft now
