### ISSUE TITLE
Genbank source modifier export from PHA4GE template: change separator in isolation-source

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#186]
Right now we are concatenating isolation source fields into the "isolation-source" field in the Genbank source modifiers export from the PHA4GE template.

The separator between the pieces of information right now is a |
e.g. Nasopharynx (NP)|Swab

It needs to be a colon as NCBI is picky about separators.
e.g.
Nasopharynx (NP):Swab

Can we change the separators pretty please?

**Comment by ddooley** [comment]
This is fixed in draft now
