### ISSUE TITLE
NML LIMS export from CanCOGeN template: change null values to all caps with underscores

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#187]
In the NML LIMS export from the CanCOGeN template, the null values are in title case (oops, cuz I asked you to change that but it's not right - my bad).

Can we make the null values all caps with underscores between words where applicable e.g.
MISSING
NOT_APPLICABLE
NOT_PROVIDED
NOT_COLLECTED
RESTRICTED_ACCESS

Thanks!

**Comment by ddooley** [comment]
This is revised on draft (master), and tested.
