### ISSUE TITLE
PHA4GE template to GISIAD export: need short form of field names to appear in top row

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#188]
In the GISAID export from the PHA4GE template, the top row requires short forms of the field names
e.g.
![image](https://user-images.githubusercontent.com/4642991/118525301-e1691300-b6f3-11eb-8840-7b67d85c1e9e.png)

We export "Virus name" from the template, but we need "covv_virus_name" to appear in the top row.

Can we get the first row to always be populated by these same values?
You can see what I mean and find the values in the submission template attached.
[20210222_EpiCoV_BulkUpload_Template.xls](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/6495425/20210222_EpiCoV_BulkUpload_Template.xls)

**Comment by ddooley** [comment]
done!
