### ISSUE TITLE
PHA4GE template to GISIAD export: change separators

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#189]
I think that a | as a separator may cause problems during upload to GISAID.

Under "Specimen source" in the export, can we have a comma separate the parts?
![image](https://user-images.githubusercontent.com/4642991/118526197-dd89c080-b6f4-11eb-840e-150a60ef05a6.png)

Under "Assembly method" in the export, can we just have a space between the consensus software name and version number?
![image](https://user-images.githubusercontent.com/4642991/118526158-cf3ba480-b6f4-11eb-910e-afa7f4ed6b77.png)

**Comment by ddooley** [comment]
done!
