### ISSUE TITLE
CanCOGeN template: enable null values for Sequencing Instrument

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#191]
In the DH CanCOGeN template, there is a pick list for Sequencing Instrument. It is a multi-select.
The DH template shows that null values should be available (in the data status field), but they don't show up in the pick list.

Can we make sure these are an option?

We just had an instance where some datasets had to supply a null value for now but will be updated later, and we had to leave to blank which will cause an error during validation.

**Comment by ddooley** [comment]
Looks like null value selections aren't being added to multi-select fields.

**Comment by griffie** [comment]
Is there a way to fix that? (asks she hopefully)

**Comment by ddooley** [comment]
yes, its a bug!  Will resolve shortly.

**Comment by griffie** [comment]
Champion! (as my dad would say)

**Comment by ddooley** [comment]
Fixed in latest draft.
