### ISSUE TITLE
CanCOGeN template: expand the CV terms for column `sample collected by`

### ISSUE THREAD

**Issue by lindaxiang** [Public-Health-Bioinformatics/DataHarmonizer#193]
The column `sample collected by` has changed to CV term list from free text. 
Virusseq portal (https://virusseq-dataportal.ca/) has accepted data with following values which are NOT in the CV term list:
- Unity Health Toronto
- Queen’s University / Kingston Health Sciences Centre

Could you please add the above values into the CV terms list? 

Thanks.

**Comment by cmrn-rhi** [comment]
Thank you for letting us know. 

The `sample collected by` term list has now been updated to include both the aforementioned values.
These changes will be reflected in the next release.

**Comment by cmrn-rhi** [comment]
The requested terms are now available in the [v0.13.29](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/releases/tag/v0.13.29) release.
