### ISSUE TITLE
Adding SOP for PHA4GE template in DataHarmonizer and website

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#195]
The CanCOGeN SOP is a bit different compared to the PHA4GE SOP.
Can we make the PHA4GE SOP available in the Help section when someone selects the PHA4GE template?
The pdf is attached.

[PHA4GE DataHarmonizer Manual_1.0.pdf](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/files/6659120/PHA4GE.DataHarmonizer.Manual_1.0.pdf)

Can we also make the link more publicly available/give it a permanent home rather than just in my google docs?
i.e. can we link the doc on in a PHA4GE section on the Wiki?
https://docs.google.com/document/d/1SwGU7qS9EL6V-r4OUKzjCrUYb6Fqwg6l2lrennWZ_GY/edit?usp=sharing

**Comment by cmrn-rhi** [comment]
PHA4GE SOP is now associated the corresponding template: https://github.com/Public-Health-Bioinformatics/DataHarmonizer/blob/master/template/pha4ge/SOP.pdf 

And it has also been linked to in the PHA4GE wiki: https://github.com/Public-Health-Bioinformatics/DataHarmonizer/wiki/PHA4GE-SARS-CoV-2-Template
