### ISSUE TITLE
CanCOGeN template export to NML-LIMS format

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#200]
In the CanCOGeN template, the export in NML LIMS format has PH_INSTRUMENT_CGN and PH_SAMPLING_DETAILS being reported after the DH provenance (DH provenance is called HC_COMMENT. After that field all the lower case DH-specific vocab appears. Before the HC_COMMENTS field all the stuff NML cares about is reported in all caps).

Can we move PH_INSTRUMENT_CGN just after PH_REASON_FOR_SEQUENCING_DETAILS?
And can we move PH_SAMPLING_DETAILS  just after HC_SAMPLE_CATEGORY?

Thanks!

**Comment by ddooley** [comment]
Done for next release!
