### ISSUE TITLE
PRIORITY: CanCOGeN template Age Bin info gets overwritten when null values entered into Host Age field

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#201]
When information about age is programmatically provided in the DH, the age bin info gets overwritten when null values are provided in the Host Age field i.e. they are providing the bins but not the actual ages. Is there a way to fix this? 

Data providers are having difficulty providing harmonized contextual data in their submission to the national db until this is fixed, so is a high priority for troubleshooting.

Thanks!

**Comment by ddooley** [comment]
I am having difficulty replicating this in v0.13.32.  I can enter values into age bin, and then null values into Host Age and these don't affect age bin values.

**Comment by ddooley** [comment]
This was resolved with an apparent workaround at one user's end. Awaiting any further details to see if there is anything to revise at DH end.
