### ISSUE TITLE
CanCOGeN template: adding a new null value to the Diagnostic PCR Ct Value fields

### ISSUE THREAD

**Issue by griffie** [Public-Health-Bioinformatics/DataHarmonizer#206]
Right now the Diagnostic PCR Ct Value fields allow for numerical values and the standard set of null values to be entered. However, sometimes labs will carry out an RT-qPCR test and get an indeterminate result. Indeterminate results don't really have an equivalent in the current set of null values (Missing, Not Applicable, Not Provided, Not Collected, Restricted Access) as the info is applicable, was collected and provided, but the result is unclear.

We would like to add a new null value for the PCR fields only (but there are 3 i.e. Diagnostic PCR Ct Value 1, Diagnostic PCR Ct Value 2, Diagnostic PCR Ct Value 3). That value is called "Indeterminate".

This value should export to the LIMS export format directly as it is in the DH (i.e. Indeterminate).

Thanks!

**Comment by ddooley** [comment]
Ok, I think this only needs a vocabulary update - to add this value to the null value list for those fields.  Has it been added there?

**Comment by griffie** [comment]
Yessir, indeed it has.

**Comment by ddooley** [comment]
Ok its updated and will be included in next release

**Comment by ddooley** [comment]
Hmm, I'm seeing no null value lists for Diagnostic PCR Ct Value 1 etc.  I would add them, and add "Indeterminate" to their lists.  This provides a pulldown menu for these fields.

**Comment by ddooley** [comment]
Done
