### ISSUE TITLE
Improve mapping to GISAID field "Passage details/history"

### ISSUE THREAD

**Issue by ivansg44** [Public-Health-Bioinformatics/DataHarmonizer#70]
Prepend `specimen processing` if  `"virus passage"` was selected.

Replace all "unknown" values with blanks. So no more "lab host;unknown;passage method".

Suggested algorithm:

    If virus passage is selected from specimen processing:
      Add virus passage

    If lab host is selected and not null value:
      Add lab host
    If passage number is selected and not a null value:
      Add passage number
    If passage method is selected and not a null value:
      Add passage method`

**Comment by ivansg44** [comment]
@griffie Is this the only GISAID field we have to worry about? Are there any other concatenated fields that you want to replace `"unknown"` values with blanks?

**Comment by griffie** [comment]
Hmmm, I think Specimen Source too. There are 7 possible fields, all yellow, but not all may apply to the sample so there will be null values in some of them. Can we just concatenate info from the fields with no null values e.g. concatenate "nasophrynx" from anatomical part and "swab" from collection device, but ignore the other fields if they just have "not applicable"?

**Comment by ivansg44** [comment]
I can do that. So every field with multiple mapped values, right?

**Comment by griffie** [comment]
Yes, I think so.
