### ISSUE TITLE
'Help'/'Support' Section in Validator

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#76]
This may have been discussed in the past (my apologies if I touch on things that have already been addressed) but can he include a 'help'/'support' section that directs the users to:
- The SOP
- Where to make issue/term requests (either linking to GitHub Issues or to a curator email)

There is now a [published version of the SOP](https://docs.google.com/document/d/e/2PACX-1vR4UkqrLaj1-9jxmrNk9mZ4S4Siim8onPHqgdXKd9m1lOroXmekClfPsXlqgFDio1rWZW7lHArSAbOg/pub) that we can link too (it will update every time we edit the SOP gdoc), but perhaps we should also have a pdf copy that users can use if they are offline? That latter would certainly require more maintenance - we could include a note at the top that it may not be the latest version and to go to the published version if possible.

**Comment by cmrn-rhi** [comment]
I see that there is a pdf version of the SOP - so ignore that recommendation (although perhaps we should still add the published link somewhere).

**Comment by ivansg44** [comment]
Another thing to add to this menu is a link to the reference guide.

**Comment by cmrn-rhi** [comment]
@ivansg44 Is there a separate reference guide outside of the SOP and in-validator field guidance?

**Comment by ivansg44** [comment]
[reference.html](https://github.com/Public-Health-Bioinformatics/DataHarmonizer/blob/master/reference.html) in the root directory courtesy of @ddooley

**Comment by ddooley** [comment]
Yes, the reference.html is automatically generated version of the label / definition / guidance and examples fields of the vocabulary.  It differs from SOP but could be linked from there too.
