### ISSUE TITLE
Failed Import Notification

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#79]
When an import fails (e.g. someone is missing a row and then fails to correctly declare which row has the column headers) it would be nice to have a notification of failed import. Especially since a failed import doesn’t show a new/empty sheet if the user has already been using it to validate a previous one. Depending on the user's attention to detail, they may not recognize that they are still working on their previous upload and proceed to work/export as if they were on the expected import.

**Comment by ivansg44** [comment]
> Especially since a failed import doesn’t show a new/empty sheet...

Could you attach a file that reproduces this bug on import? I tried opening a file with the first row removed, and declared the headers to be on an empty row, and it creates a new/empty sheet.
