### ISSUE TITLE
Invalid Data Notification on Save/Export

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#80]
Could have a notification for when a user tries to export/save a validated spreadsheet that has invalid fields. We don't want to prevent export, but this could be helpful for users who may have missed correcting a field by accident. Perhaps the notification could have a 'more info' option that would then list out the invalid cells.

**Comment by ivansg44** [comment]
@wwhsiao raised the possibility of not allowing export at all if the spreadsheet has invalid cells.

But I like the idea of having this notification on save.

**Comment by ddooley** [comment]
Definitely allow save with errors.  Errors can take multiple work sessions to resolve completely.

**Comment by ivansg44** [comment]
To clarify, @wwhsiao raised the possibility of stopping export to... not save as...

**Comment by ddooley** [comment]
Ah, of course!
