### ISSUE TITLE
Improve Spreadsheet Navigation

### ISSUE THREAD

**Issue by cmrn-rhi** [Public-Health-Bioinformatics/DataHarmonizer#81]
It would be nice to have a way to search for and go to a column based on it's header.
With the headers not being alphabetical, and ctrl+f only working for the text currently displayed in the viewport, it can be frustrating trying to navigate to a specific column. E.g. I know I want to edit 'host age' but I can't recall where it is in the spreadsheet, so I have to slowly scroll through the sheet to find it. This gets tedious quickly and will only get more frustrating overtime as we add more fields. 

Is there a way we could have a header search of some sort? When the user types input, it pulls from a header pick-list and then takes you to your selection. Perhaps using something like [scrollViewportTo()](https://handsontable.com/docs/1.17.0/Core.html#scrollViewportTo) - with the header names mapped to a header col number that it jumps you to? 
[scrollViewportTo jsfiddle example](http://jsfiddle.net/0ubtkvwc/)

**Comment by ddooley** [comment]
nice feature idea.  Possibly it could be a pulldown list of all columns in sheet, organized hierarchically.
