### ISSUE TITLE
Improve performance with large datasets

### ISSUE THREAD

**Issue by ivansg44** [Public-Health-Bioinformatics/DataHarmonizer#84]
With the potential of several thousand samples needing validation from stakeholders in Quebec and Ontario, we should improve performance for larger datasets. Telling users to break their data up into chunks should be a last resort.

Scrolling through large datasets is fine, due to only a subset of the data being rendered.

Importing, saving and exporting large datasets freezes the page for a significant amount of time. The bottleneck seems to be the ability of Sheet-JS to read/write large files. Sheet-JS has a `XLSX.writeFileAsync` file that's worth investigating. For reading, perhaps we can break the binary string Filereader obtains into chunks and have Sheet-JS read them in parallel using promises.

Validating large datasets freezes the page for an **incredibly significant amount of time**. The bottleneck seems to be with Handsontable's `updateSettings` function. Perhaps we can take a different approach, that involves iterating through the matrix in parallel and making calls to `hot.setCellMeta`.

Webworkers could also be useful. We could offload the tasks to the background and provide a loading dialog. Webworkers don't work in Chrome offline, but there may be a workaround https://stackoverflow.com/a/33432215/11472358

**Comment by ivansg44** [comment]
I don't think web workers are ideal. There seems to be so many hang-ups and work-arounds required to get them working from a `file:///` origin, that it doesn't seem like a stable enhancement. We should just attempt to limit the page freezes to as few seconds as possible.

**Comment by ddooley** [comment]
Yeah, I believe that.  One other approach would be a "validation" toggle setting which only validates the cells currently being refreshed in a view port?  If the issue is that validating a giant shebang of records takes a long time, but the only way one is going to see that work is if one scrolls to it, then just validating the viewport, if its fast enough, would solve things?

**Comment by ivansg44** [comment]
Good news is that I was able to reduce validation time for ~10 000 cells from ~30 seconds to ~3 seconds on my machine 
0117112. I think that's acceptable. I'm trying to improve time needed to open and save files now.

**Comment by ddooley** [comment]
Great!
